
```{r}
#read data
setwd("C:/Users/vishrti/Desktop/ML webinar")
library(openxlsx)
dhcb<-read.xlsx("DCHB_Village_Release_0600 v1.xlsx")
```
```{r}
dim(dhcb)
#colnames(dhcb)
dhcb_irrig<-dhcb[,c(2:8,76:81,153:160)]
colnames(dhcb_irrig)

#summary(dhcb_irrig)



dim(dhcb_irrig)
dhcb_irrig_small<-dhcb_irrig[dhcb_irrig$Total.Population.of.Village<1000,]
dhcb_irrig_medium<-filter(dhcb_irrig, Total.Population.of.Village >= 1000 & Total.Population.of.Village <= 2500)

dhcb_irrig_high<-dhcb_irrig[dhcb_irrig$Total.Population.of.Village>2500,]


dim(dhcb_irrig_small)
dim(dhcb_irrig_medium)
dim(dhcb_irrig_high)

summary(dhcb_irrig_small)

dhcb_irrig_small$`Canals.Area.(in.Hectares)` = ifelse(is.na(dhcb_irrig_small$`Canals.Area.(in.Hectares)`),39.9,dhcb_irrig_small$`Canals.Area.(in.Hectares)`) #because mean is 39.9


sum(is.na(dhcb_irrig_small))

colnames(dhcb_irrig_small)

```

```{r}
dhcb_irrig_small.Scaled <- scale(dhcb_irrig_small[,c(3:5,8:21)])
dhcb_irrig_medium.Scaled <- scale(dhcb_irrig_medium[,c(3:5,8:21)])
dhcb_irrig_high.Scaled <- scale(dhcb_irrig_high[,c(3:5,8:21)])


colnames(dhcb_irrig_high.Scaled)

head(dhcb_irrig_medium.Scaled)
str(dhcb_irrig_medium.Scaled)


sum(is.na(dhcb_irrig_medium.Scaled))

```
```{r}
head(dhcb_irrig_small.Scaled)
str(dhcb_irrig_small.Scaled)


sum(is.na(dhcb_irrig_small.Scaled))
```
```{r}
head(dhcb_irrig_high.Scaled)
str(dhcb_irrig_high.Scaled)


sum(is.na(dhcb_irrig_high.Scaled))
```

```{r}
# removing columns which have 0 variance for this set of data

dhcb_irrig_small.Scaled1<-dhcb_irrig_small.Scaled

dhcb_irrig_medium.Scaled1<-dhcb_irrig_medium.Scaled

dhcb_irrig_high.Scaled1<-dhcb_irrig_high.Scaled

dim(dhcb_irrig_small.Scaled1)
dim(dhcb_irrig_medium.Scaled1)
dim(dhcb_irrig_high.Scaled1)
```


```{r}

wssplot <- function(data, nc=15, seed=3110){
  wss <- (nrow(data)-1)*sum(apply(data,2,var))
  for (i in 2:nc){
    set.seed(seed)
    wss[i] <- sum(kmeans(data, centers=i)$withinss)}
  plot(1:nc, wss, type="b", xlab="Number of Clusters",
       ylab="Within groups sum of squares")}


wssplot(dhcb_irrig_small.Scaled1, nc=5)
wssplot(dhcb_irrig_medium.Scaled1, nc=5)
wssplot(dhcb_irrig_high.Scaled1, nc=5)


```

```{r}
kmeans.clus1 = kmeans(x=dhcb_irrig_small.Scaled1, centers = 4, nstart = 3)

kmeans.clus2 = kmeans(x=dhcb_irrig_medium.Scaled1, centers = 4, nstart = 3)

kmeans.clus3 = kmeans(x=dhcb_irrig_high.Scaled1, centers = 4, nstart = 3)

dhcb_irrig_small$Clusters <- kmeans.clus1$cluster

dhcb_irrig_medium$Clusters <- kmeans.clus2$cluster

dhcb_irrig_high$Clusters <- kmeans.clus3$cluster

aggr_irrig_small = aggregate(dhcb_irrig_small[,-c(1,2)],list(dhcb_irrig_small$Clusters),mean)
aggr_irrig_medium =aggregate(dhcb_irrig_medium[,-c(1,2)],list(dhcb_irrig_medium$Clusters),mean)

aggr_irrig_high =aggregate(dhcb_irrig_high[,-c(1,2)],list(dhcb_irrig_high$Clusters),mean)



aggr_irrig_small


```

```{r}
write.csv(dhcb_irrig_small,file="dhcb_irrig_small_rmd.csv")
write.csv(dhcb_irrig_medium,file="dhcb_irrig_medium_rmd.csv")
write.csv(dhcb_irrig_high,file="dhcb_irrig_high_rmd.csv")



write.csv(aggr_irrig_small,file="dhcb_irrig_small1_rmd.csv")
write.csv(aggr_irrig_medium,file="dhcb_irrig_medium1_rmd.csv")
write.csv(aggr_irrig_high,file="dhcb_irrig_high1_rmd.csv")

```
